language: objective-c
osx_image: xcode7.2
before_install:
  - brew update
  - brew reinstall xctool
  - gem install cocoapods -v 0.38.2
  - pip install codecov
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=tests
  - MODE=examples
  - MODE=life-without-cocoapods
  - MODE=framework
script: ./build.sh $MODE
after_success:
  - codecov

# whitelist
branches:
  only:
    - master
