language: objective-c
osx_image: xcode7.2
before_install:
  - brew update
  - brew reinstall xctool
  - gem install cocoapods -v 0.38.2
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=tests
  - MODE=examples
  - MODE=life-without-cocoapods
  - MODE=framework
script: 
  - set -o pipefail
  - xcodebuild test -project AsyncDisplayKit.xcodeproj -sdk iphonesimulator -scheme AsyncDisplayKit-iOS -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
  - ./build.sh $MODE
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

# whitelist
branches:
  only:
    - master
