language: objective-c
osx_image: xcode7.2
before_install:
  - brew update
  - brew reinstall xctool
  - gem install cocoapods -v 0.38.2
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=tests
  - MODE=examples
  - MODE=life-without-cocoapods
  - MODE=framework
script: 
  - set -o pipefail
  - ./build.sh $MODE
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

# whitelist
branches:
  only:
    - master
